# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: check file
      run: ls -l
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        path: ./kram

    - name: Upload to Release Action
      # You may pin to the exact commit or the version.
      # uses: Shopify/upload-to-release@9942a4c936dab172f7101dcc7dc20528ea949102
      env:
          API_TOKEN_GITHUB: ${{ secrets.ReposTokenAccess }}
      uses: Shopify/upload-to-release@v1.0.1
      with:
        # Artifact name
        name: kram
        # Path to the file to upload
        path: ./
        # secrets.GITHUB_TOKEN
        repo-token: ${{ secrets.ReposTokenAccess }}
      
